/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.CarDb;
import model.carDbHistory;

/**
 *
 * @author Dell
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    carDbHistory history;
    
    public CreateJPanel(carDbHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblManufaturer = new javax.swing.JLabel();
        lblYearofManufacturing = new javax.swing.JLabel();
        lblnumSeats = new javax.swing.JLabel();
        lblModelnum = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        txtManufacturer1 = new javax.swing.JTextField();
        txtYearofManufacturing1 = new javax.swing.JTextField();
        txtnumSeats1 = new javax.swing.JTextField();
        txtmodelNum1 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREATE DATABASE OF THE CAR");

        lblManufaturer.setText("Manufacturer:");

        lblYearofManufacturing.setText("Year of Manufacturing:");

        lblnumSeats.setText("Number of Seats:");

        lblModelnum.setText("Model Number:");

        lblcity.setText("City:");

        txtYearofManufacturing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearofManufacturing1ActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblcity)
                            .addComponent(lblModelnum)
                            .addComponent(lblnumSeats)
                            .addComponent(lblYearofManufacturing)
                            .addComponent(lblManufaturer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtYearofManufacturing1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufacturer1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodelNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnSave)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufaturer)
                    .addComponent(txtManufacturer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearofManufacturing)
                    .addComponent(txtYearofManufacturing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumSeats)
                    .addComponent(txtnumSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelnum)
                    .addComponent(txtmodelNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(btnSave)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
       String manufacturer=txtManufacturer1.getText();
     int Year=Integer.parseInt(txtYearofManufacturing1.getText());
    int minSeat=Integer.parseInt(txtnumSeats1.getText());
     long modelNum=Long.parseLong(txtmodelNum1.getText());
     String city=txtcity.getText();
     CarDb d= history.addNewData();
    
     if(manufacturer.isEmpty())
     {
          JOptionPane.showMessageDialog(this, "Please add name of Manufacturer."); 
     }
    
     else
     {
     d.setManufacturer(manufacturer);  
       
     d.setMinSeat(minSeat);
     d.setModelNum(modelNum);
     d.setYear(Year);
     d.setCity(city);

     
     JOptionPane.showMessageDialog(this, "New Record added.");
     
     txtManufacturer1.setText("");
     txtYearofManufacturing1.setText("");
     txtnumSeats1.setText("");
     txtmodelNum1.setText("");
     txtcity.setText("");
   
             } 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtYearofManufacturing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearofManufacturing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearofManufacturing1ActionPerformed
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblManufaturer;
    private javax.swing.JLabel lblModelnum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYearofManufacturing;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblnumSeats;
    private javax.swing.JTextField txtManufacturer1;
    private javax.swing.JTextField txtYearofManufacturing1;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtmodelNum1;
    private javax.swing.JTextField txtnumSeats1;
    // End of variables declaration//GEN-END:variables
}
