/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.CarDb;
import model.carDbHistory;
 import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class SearchJPanel extends javax.swing.JPanel 
{
   
    /**
     * Creates new form SearchJPanel
     */
     carDbHistory history;
    public SearchJPanel(carDbHistory history) {
        initComponents();
         this.history= history;
        populateTable();
        
         populateCombo();
         populateCombo1();
         populatefilterCar();
    }

   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcar = new javax.swing.JTable();
        modelNum = new javax.swing.JButton();
        jCombo_mName = new javax.swing.JComboBox<>();
        YofManufact = new javax.swing.JButton();
        jCombo_YofManuf = new javax.swing.JComboBox<>();
        btnseats = new javax.swing.JButton();
        Mname1 = new javax.swing.JButton();
        txtmodelnum = new javax.swing.JTextField();
        btncity = new javax.swing.JButton();
        txtcity = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        lbltitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("SEARCH IN THE DATABASE");

        tblcar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "Year of Manufacturing", "Minimum Seat", "Model Number", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcar);

        modelNum.setText("Model Number:");
        modelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNumActionPerformed(evt);
            }
        });

        jCombo_mName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombo_mName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_mNameActionPerformed(evt);
            }
        });

        YofManufact.setText("Year of Manufacturing:");

        jCombo_YofManuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombo_YofManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_YofManufActionPerformed(evt);
            }
        });

        btnseats.setText("Number of Seats:");

        Mname1.setText("Manufacture name:");

        btncity.setText("City:");

        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnseats)
                    .addComponent(YofManufact)
                    .addComponent(Mname1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCombo_YofManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncity))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCombo_mName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(modelNum))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmodelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(btnsearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbltitle)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombo_mName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mname1)
                    .addComponent(txtmodelnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNum))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncity)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YofManufact)
                            .addComponent(jCombo_YofManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnseats)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btnsearch)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCombo_mNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_mNameActionPerformed
         populatefilterCar();
    }//GEN-LAST:event_jCombo_mNameActionPerformed

    private void jCombo_YofManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_YofManufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_YofManufActionPerformed

    private void modelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mname1;
    private javax.swing.JButton YofManufact;
    private javax.swing.JButton btncity;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnseats;
    private javax.swing.JComboBox<String> jCombo_YofManuf;
    private javax.swing.JComboBox<String> jCombo_mName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JButton modelNum;
    private javax.swing.JTable tblcar;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtmodelnum;
    // End of variables declaration//GEN-END:variables

    private void populateTable()
    {

        DefaultTableModel model=  (DefaultTableModel) tblcar.getModel();
        model.setRowCount(0);
        
        for(CarDb d :history.getHistory())
        {
            Object[] row= new Object[5];
            row[0]=d.getManufacturer();
            row[1]= d.getYear();
            row[2]= d.getMinSeat();
            row[3]= d.getModelNum();
            row[4]= d.getCity();
            
            model.addRow(row); 

    }
    }

    private void populateCombo() 
    {
        
        jCombo_mName.removeAllItems();
        for(CarDb d :history.getHistory())
        {
            jCombo_mName.addItem(d.getManufacturer());           
    }
}

    private void populateCombo1() 
    {
        jCombo_YofManuf.removeAllItems();
        for(CarDb d :history.getHistory())
        {
            jCombo_YofManuf.addItem(String.valueOf(d.getYear()));           
    }
    }

    private void populatefilterCar() 
    {
   
    }
}